// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"micro-services/sdk/models"
)

// CreateProdcutReader is a Reader for the CreateProdcut structure.
type CreateProdcutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateProdcutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateProdcutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewCreateProdcutUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 501:
		result := NewCreateProdcutNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateProdcutOK creates a CreateProdcutOK with default headers values
func NewCreateProdcutOK() *CreateProdcutOK {
	return &CreateProdcutOK{}
}

/* CreateProdcutOK describes a response with status code 200, with default header values.

A list of products
*/
type CreateProdcutOK struct {
	Payload []*models.Product
}

// IsSuccess returns true when this create prodcut o k response has a 2xx status code
func (o *CreateProdcutOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create prodcut o k response has a 3xx status code
func (o *CreateProdcutOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create prodcut o k response has a 4xx status code
func (o *CreateProdcutOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create prodcut o k response has a 5xx status code
func (o *CreateProdcutOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create prodcut o k response a status code equal to that given
func (o *CreateProdcutOK) IsCode(code int) bool {
	return code == 200
}

func (o *CreateProdcutOK) Error() string {
	return fmt.Sprintf("[POST /products][%d] createProdcutOK  %+v", 200, o.Payload)
}

func (o *CreateProdcutOK) String() string {
	return fmt.Sprintf("[POST /products][%d] createProdcutOK  %+v", 200, o.Payload)
}

func (o *CreateProdcutOK) GetPayload() []*models.Product {
	return o.Payload
}

func (o *CreateProdcutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateProdcutUnprocessableEntity creates a CreateProdcutUnprocessableEntity with default headers values
func NewCreateProdcutUnprocessableEntity() *CreateProdcutUnprocessableEntity {
	return &CreateProdcutUnprocessableEntity{}
}

/* CreateProdcutUnprocessableEntity describes a response with status code 422, with default header values.

Validation errors defined as an array of strings
*/
type CreateProdcutUnprocessableEntity struct {
	Payload *models.ValidationError
}

// IsSuccess returns true when this create prodcut unprocessable entity response has a 2xx status code
func (o *CreateProdcutUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create prodcut unprocessable entity response has a 3xx status code
func (o *CreateProdcutUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create prodcut unprocessable entity response has a 4xx status code
func (o *CreateProdcutUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this create prodcut unprocessable entity response has a 5xx status code
func (o *CreateProdcutUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this create prodcut unprocessable entity response a status code equal to that given
func (o *CreateProdcutUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

func (o *CreateProdcutUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /products][%d] createProdcutUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CreateProdcutUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /products][%d] createProdcutUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CreateProdcutUnprocessableEntity) GetPayload() *models.ValidationError {
	return o.Payload
}

func (o *CreateProdcutUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateProdcutNotImplemented creates a CreateProdcutNotImplemented with default headers values
func NewCreateProdcutNotImplemented() *CreateProdcutNotImplemented {
	return &CreateProdcutNotImplemented{}
}

/* CreateProdcutNotImplemented describes a response with status code 501, with default header values.

Generic error message returned as a string
*/
type CreateProdcutNotImplemented struct {
	Payload *models.GenericError
}

// IsSuccess returns true when this create prodcut not implemented response has a 2xx status code
func (o *CreateProdcutNotImplemented) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create prodcut not implemented response has a 3xx status code
func (o *CreateProdcutNotImplemented) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create prodcut not implemented response has a 4xx status code
func (o *CreateProdcutNotImplemented) IsClientError() bool {
	return false
}

// IsServerError returns true when this create prodcut not implemented response has a 5xx status code
func (o *CreateProdcutNotImplemented) IsServerError() bool {
	return true
}

// IsCode returns true when this create prodcut not implemented response a status code equal to that given
func (o *CreateProdcutNotImplemented) IsCode(code int) bool {
	return code == 501
}

func (o *CreateProdcutNotImplemented) Error() string {
	return fmt.Sprintf("[POST /products][%d] createProdcutNotImplemented  %+v", 501, o.Payload)
}

func (o *CreateProdcutNotImplemented) String() string {
	return fmt.Sprintf("[POST /products][%d] createProdcutNotImplemented  %+v", 501, o.Payload)
}

func (o *CreateProdcutNotImplemented) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *CreateProdcutNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
